set(DEBUG_MACRO_PREFIX_DIR ${THIRD_PARTY_PATH}/dbg_macro)
set(DEBUG_MACRO_INSTALL_DIR ${THIRD_PARTY_PATH}/dbg_macro)
set(DEBUG_MACRO_INCLUDE_DIR "${DEBUG_MACRO_INSTALL_DIR}")
set(DEBUG_MACRO_SOURCE_DIR ${PROJECT_SOURCE_DIR}/third_party/dbg_macro)
set(DEBUG_MACRO_LIBRARIES "${DEBUG_MACRO_INSTALL_DIR}/lib/dbg_macro.a")

include_directories(${DEBUG_MACRO_INCLUDE_DIR})

include(ExternalProject)
ExternalProject_Add(
  extern_dbg_macro
  SOURCE_DIR ${DEBUG_MACRO_SOURCE_DIR}
  PREFIX ${DEBUG_MACRO_PREFIX_DIR}
  CONFIGURE_COMMAND ""
  BUILD_COMMAND ""
  INSTALL_COMMAND make PREFIX=${DEBUG_MACRO_INSTALL_DIR} install
  TEST_COMMAND ""
  BUILD_IN_SOURCE 1
  BUILD_BYPRODUCTS ${DEBUG_MACRO_LIBRARIES}
)

add_library(dbg_macro STATIC IMPORTED GLOBAL)
set_property(TARGET dbg_macro PROPERTY IMPORTED_LOCATION ${DEBUG_MACRO_LIBRARIES})
add_dependencies(dbg_macro extern_dbg_macro)
